sharamin/config/routes.rb
Rails.application.routes.draw do
  resources :resumes
  resources :user
	get 'hacker_spots/index'

	resources :posts
	get '/' => "posts#index"

	post '/user/register' => "user#register"
	post '/user/login' => "user#login"
	post '/user/logout' => "user#logout"

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

sharamin/app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
	mount_uploader :logo_img, ClubLogoUploader
end

sharamin/app/models/resume.rb
class Resume < ApplicationRecord
end

sharamin/app/models/user.rb
class User < ApplicationRecord
end

sharamin/app/controllers/api_controller.rb
class ApiController < ActionController::Base
	def require_token_authentication
		authenticate_token || render_unauthorized("Access denied")
	end

	def current_user
		@current_user ||= authenticate_token
	end

	protected

	def render_unauthorized(message)
		errors = { errors: [ { detail: message } ] }
		render json: errors, status: :unauthorized
	end

	private

	def authenticate_token
		authenticate_with_http_token do |token, options|
			if user = User.with_unexpired_token(token, 2.days.ago)
				# Compare the tokens in a time-constant manner, to mitigate timing attacks.
				ActiveSupport::SecurityUtils.secure_compare(
					::Digest::SHA256.hexdigest(token),
					::Digest::SHA256.hexdigest(user.token))
					user
			end
		end
	end  
end

sharamin/app/controllers/hacker_spots_controller.rb
class HackerSpotsController < ApiController
	before_action :require_token_authentication

	# This is protected by API token
	def index
		render json: { spots: 'List of places to work in coffee shops'}
	end
end

sharamin/app/controllers/posts_controller.rb
class PostsController < ApplicationController
	skip_before_filter :verify_authenticity_token
  before_action :set_post, only: [:show, :edit, :update, :destroy]


  # GET /posts
  # GET /posts.json
	
  def index
	@menu = "view"
	query = params[:q];
	if query
		@posts = Post.where("club LIKE ?", "%#{query}%")
	else
		@posts = Post.all
	end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
	@menu = "view"
	puts params[:id]
	@resumes = Resume.where(post_id: params[:id])
  end

  # GET /posts/new
  def new
	@menu = "recruit"
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
	@menu = "recruit"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
	@post.user_id = session[:user_id]
	puts post_params

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:club, :deadline, :target, :recruit_type, :homepage, :description, :attachment, :etc, :logo_img, :user_id, :questions)
	end
end

sharamin/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  # GET /resumes
  # GET /resumes.json
  def index
    @resumes = Resume.all
  end

  # GET /resumes/1
  # GET /resumes/1.json
  def show
  end

  # GET /resumes/new
  def new
	p = params[:p]
	@post = Post.find(p);
    @resume = Resume.new
  end

  # GET /resumes/1/edit
  def edit
  end

  # POST /resumes
  # POST /resumes.json
  def create
    @resume = Resume.new(resume_params)
	@resume.user_id = session[:user_id]

    respond_to do |format|
      if @resume.save
        format.html { redirect_to "/posts/".concat(@resume.post_id.to_s), notice: 'Resume was successfully created.' }
        format.json { render :show, status: :created, location: @resume }
      else
        format.html { render :new }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resumes/1
  # PATCH/PUT /resumes/1.json
  def update
    respond_to do |format|
      if @resume.update(resume_params)
        format.html { redirect_to @resume, notice: 'Resume was successfully updated.' }
        format.json { render :show, status: :ok, location: @resume }
      else
        format.html { render :edit }
        format.json { render json: @resume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resumes/1
  # DELETE /resumes/1.json
  def destroy
    @resume.destroy
    respond_to do |format|
      format.html { redirect_to resumes_url, notice: 'Resume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resume
      @resume = Resume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resume_params
      params.fetch(:resume, {})
      params.require(:resume).permit(:name, :dept, :id_num, :degree, :position, :answers, :post_id)
    end
end

sharamin/app/controllers/sessions_controller.rb
class SessionsController < ApiController
	skip_before_action :require_token_authentication, only: [:create], raise: false

	def create
		if user = User.valid_login?(params[:email], params[:password])
			user.allow_token_to_be_used_only_once
			send_auth_token_for_valid_login_of(user)
		else
			render_unauthorized("Error with your login or password")
		end
	end

	def destroy
		current_user.logout
		head :ok
	end

	private

	def send_auth_token_for_valid_login_of(user)
		render json: { token: user.token }
	end
end

sharamin/app/controllers/user_controller.rb
class UserController < ApplicationController
	def register
		u = User.new
		u.name = params[:name]
		u.email = params[:email]
		u.pw = params[:pw]
		u.save
		u = User.where(:email => params[:email],
					   :pw => params[:pw]).take
		session[:user_id] = u.id
	end

	def login
		u = User.where(:email => params[:email],
					   :pw => params[:pw]).take
		session[:user_id] = u.id
	end

	def logout
		reset_session
	end
end

sharamin/app/helpers/api_helper.rb
module ApiHelper
end

sharamin/app/helpers/posts_helper.rb
module PostsHelper
end

sharamin/app/helpers/resumes_helper.rb
module ResumesHelper
end

sharamin/app/helpers/user_helper.rb
module UserHelper
end

sharamin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>샤람인</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <body>
	<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top ">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="/posts">ㅅF람인</a>

		<div class="collapse navbar-collapse" id="navbarsExampleDefault">
			<ul class="navbar-nav mr-auto">
				<% if @menu == "view" %>
				<li class="nav-item active">
				<% else %>
				<li class="nav-item">
				<% end %>
					<a class="nav-link" href="/posts">모집 보기<span class="sr-only">(current)</span></a>
				</li>
				<% if @menu == "recruit" %>
				<li class="nav-item active">
				<% else %>
				<li class="nav-item">
				<% end %>
					<a class="nav-link" href="/posts/new">모집 하기</a>
				</li>
				<li class="nav-item">
					<% if session[:user_id] %>
						<a id="logout" class="nav-link" href="#">로그아웃</a>
					<% else %>
						<a class="nav-link" href="#" data-toggle="modal" data-target="#login-modal">로그인</a>
					<% end %>
				</li>
			</ul>
			<form class="form-inline my-2 my-lg-0" action="/">
				<input class="form-control mr-sm-2" type="text" placeholder="동아리 검색" name="q">
				<button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Go !</button>
			</form>
		</div>
	</nav>
	<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
		<div class="modal-dialog">
			<div class="loginmodal-container">
				<h1>로그인 하세요</h1><br>
				<form>
					<input type="text" id="login_id" name="user" placeholder="ID를 입력해주세요">
					<input type="password" id="login_pw" name="pass" placeholder="비밀번호를 입력해주세요">
					<input type="button" id="btn_login" name="login" class="login loginmodal-submit" value="로그인">
				</form>

				<div class="login-help">
					<a href="#" data-toggle="modal" data-target="#signup-modal">가입하기</a>
				</div>
			</div>
		</div>
	</div>	
	<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
		<div class="modal-dialog">
			<div class="loginmodal-container">
				<h1>가입하기</h1><br>
				<form>
					<input type="text" id="reg_id" name="user" placeholder="영문, 숫자 조합">
					<input type="password" id="reg_pw" name="pass" placeholder="영문, 숫자 조합 8자 이상">
					<input type="text" id="name" name="name" placeholder="이름을 입력해주세요">
					<input type="button" id="btn_register" name="login" class="login loginmodal-submit" value="가입">
				</form>

				<div class="login-help">
					<a href="#" data-toggle="modal" data-target="#login-modal">로그인하기</a>
				</div>
			</div>
		</div>
	</div>	
    <%= yield %>
	<script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
	<script>
		$(document).ready(function() {
			$("#btn_login").click(function(e) {
				$.ajax({
					url :'/user/login',
					type:'POST',
					data: {
						email: $("#login_id").val(),
						pw: $("#login_pw").val()
					},
					success: function(data) {
						console.log(data);
						location.reload();
					}
				});
			});

			$("#btn_register").click(function(e) {
				$.ajax({
					url :'/user/register',
					type:'POST',
					data: {
						email: $("#reg_id").val(),
						pw: $("#reg_pw").val(),
						name: $("#name").val()
					},
					success: function(data) {
						console.log(data);
						location.reload();
					}
				});
			});

			$("#logout").click(function(e) {
				$.ajax({
					url :'/user/logout',
					type:'POST',
					success: function(data) {
						console.log(data);
						location.reload();
					}
				});
			});
		});
	</script>
  </body>
</html>

sharamin/app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="container">
		<div class="form-group row">
			<label for="example-text-input" class="col-2 col-form-label">단체명</label>
			<div class="col-10">
				<%= f.text_field :club, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="exampleInputFile" class="col-2 col-form-label">동아리 로고</label>
			<div class="col-10">
				<%= f.file_field :logo_img, class:'form-control-file' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">모집 기한</label>
			<div class="col-10">
				<% if post.deadline %>
				<input class="form-control" type="datetime-local" value="<%= post.deadline.strftime("%Y-%m-%dT%H:%M:%S") %>" id="example-datetime-local-input" name="post[deadline]">
				<% else %>
				<input class="form-control" type="datetime-local" id="example-datetime-local-input" name="post[deadline]">
				<% end %>
			</div>
		</div>

		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">모집 대상</label>
			<div class="col-10">
				<%= f.text_field :target, class: 'form-control', placeholder:"학부생, 대학원생, 타대생" %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">모집 부문</label>
			<div class="col-10">
				<%= f.text_field :recruit_type, class: 'form-control', placeholder:"연출팀, 기획팀 등등" %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-email-input" class="col-2 col-form-label">홈페이지 주소</label>
			<div class="col-10">
				<%= f.text_field :homepage, class:'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-email-input" class="col-2 col-form-label">기타사항</label>
			<div class="col-10">
				<%= f.text_field :etc, class:'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="exampleTextarea" class="col-2 col-form-label">모집 안내</label>
			<div class="col-10">
				<%= f.text_area :description, class:'form-control', rows:"8" %>
			</div>
		</div>
		<div class="form-group row">
			<label for="exampleInputFile" class="col-2 col-form-label">파일 첨부</label>
			<div class="col-10">
				<%= f.file_field :attachment, class:'form-control-file' %>
			</div>
		</div>
		<input id="q_val" type="hidden" name="post[questions]" value="">
		<div id="q_wrapper">
			<% if post.questions %>
				<% JSON.parse(post.questions).each_with_index do |q, index| %>
			<div class="form-group row">
				<label for="example-text-input" class="col-2 col-form-label">질문 <%= index+1 %></label>
				<div class="col-10">
					<input class="form-control" type="text" value="<%= q %>" id="example-text-input" name="">
				</div>
			</div>
			<% end %>
			<% else %>
			<div class="form-group row">
				<label for="example-text-input" class="col-2 col-form-label">질문 1</label>
				<div class="col-10">
					<input class="form-control" type="text" value="동아리에 지원하게 된 계기가 무엇입니까?" id="example-text-input">
				</div>
			</div>
			<div class="form-group row">
				<label for="example-text-input" class="col-2 col-form-label">질문 2</label>
				<div class="col-10">
					<input class="form-control" type="text" value="동아리에서 하고 싶은 역할은?" id="example-text-input">
				</div>
			</div>
			<% end %>
		</div>
		<div class="row">
      	<input type="button" id="btn_add" class="btn btn-info" value="질문 추가">
		</div>

		<div class="row text-center">
			<div class="col-sm-12">
			<button type="button" id="submit_btn" class="btn btn-lg btn-primary">새 리크루팅 작성</button>
			</div>
		</div>
	</div>
<% end %>
<script>
	$(document).ready(function() { 
		$("#btn_add").click(function(e) {
			var q_cnt = $("#q_wrapper").children().length + 1;
			$("#q_wrapper").append('<div class="form-group row"><label for="example-text-input" class="col-2 col-form-label">질문 '+q_cnt+'</label><div class="col-10"><input class="form-control" type="text"value=""id="example-text-input"></div>');

		});

		$("#submit_btn").click(function(e) {
			e.preventDefault();
			var q = [];
			$("#q_wrapper").children().each(function(i, item) {
				var v = $(item).find("input").val();
				if(v) q.push(v);
			});
			var q_str = JSON.stringify(q);
			$("#q_val").val(q_str);			
			$(this).parents('form').submit();
		});
 });
</script>

sharamin/app/views/posts/edit.html.erb
<div class="container header">
	<div class="alert alert-info">
		<strong class="font_30">리크루팅 정보를 입력하세요.</strong>
	</div>
</div>

<%= render 'form', post: @post %>

sharamin/app/views/posts/index.html.erb
<style>
.logo {
	margin-top:60px;
	text-align:center;
}

.logo_img {
	width:200px;
	height:200px;
}

body{
	color:#666;
	margin-top:20px;
	overflow-x:hidden;
}

a {
	color:#666;
	text-decoration:none;
}
#main-content li{
	border:solid #CCC;
	border-width:0 1px 1px 0;
	background:	#effbff;
	padding:10px;
	display:inline-block;
	margin: 40px 0 40px;
	border-radius:10px;
}

#main-content li img{
	width:20vw;
	height:20vw;
	max-width:200px;
	max-height:200px;
}

#main-content a div{
    height:40px;
		line-height:40px;
		text-align: center;
		font-weight:bold;
		background:#fff;
		color:#1a1a1a;
		padding:5px 0 5px 0;
		text-transform:uppercase;
		line-height:40px;
		border-width:10px 0 10px 0;
		filter: alpha(opacity=100);
}




</style>
<div class="logo">
	<%= image_tag "logo.png", class:'logo_img' %>
</div>

<div class="container-fluid">
	<div id="main-content">
	<div class="row">
		<% @posts.each do |post| %>
		<div class="col-md-3 center">
			<li>
				<a href="/posts/<%= post.id %>">
					<%= image_tag(post.logo_img.to_s) %>
					<div class="col-md-12 center"><%= post.club %></div>
				</a>
			</li>
		</div>
		<% end %>
	</div>
</div>

sharamin/app/views/posts/new.html.erb
<style>
.container {
	margin-bottom:20px;
}
</style>

<div class="container header">
	<div class="alert alert-info">
		<strong class="font_30">리크루팅 정보를 입력하세요.</strong>
	</div>
</div>

<%= render 'form', post: @post %>

sharamin/app/views/posts/show.html.erb
<div class="container header">
	<div class="alert alert-info">
		<strong class="font_30"><%= @post.club %> 신입부원 모집공고</strong>
	</div>
</div>
<div class="container">
	<div class="row club_intro">
		<%= image_tag @post.logo_img.to_s, class:'logo_img float-left' %>
		<p>
		<%= raw @post.description.gsub(/[\n\r]/,"<br/>") %>
		</p>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong>모집부문</strong>
		</div>
		<div class="col-sm-10">
			<%= @post.target %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong> 모집기간 </strong>
		</div>
		<div class="col-sm-10">
			<%= @post.deadline.strftime("%Y-%m-%d %H시 까지") %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong> 기타 사항 </strong>
		</div>
		<div class="col-sm-10">
			<%= @post.etc %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong> 홈페이지 주소 </strong>
		</div>
		<div class="col-sm-10">
			<a href="<%= @post.homepage %>" target="_blank"><%= @post.club %> 홈페이지</a>
		</div>
	</div>
	<div class="row attach_wrapper">
	<%= image_tag @post.attachment.to_s %>
	</div>
	<br>
	<br>
	<% if @post.user_id == session[:user_id] %>
	<div class="container">
		<div class="alert alert-success" role="alert">
			<strong class="font_30">지원서</strong>
		</div>
		<div id="accordion" role="tablist" aria-multiselectable="true">
			<% @resumes.each_with_index do |resume, i| %>
			<div class="card">
				<div class="card-header" role="tab" id="headingOne">
					<h5 class="mb-0">
						<a data-toggle="collapse" data-parent="#accordion" href="#collapse<%=i%>" aria-expanded="true" aria-controls="collapseOne">
							<%= resume.name %>
						</a>
					</h5>
				</div>

				<div id="collapse<%=i%>" class="collapse" role="tabpanel" aria-labelledby="headingOne">
					<div class="card-block">
						<dl class="dl-horizontal">
							<dt>이름</dt><dd><%= resume.name %></dd>
							<dt>학과</dt><dd><%= resume.dept %></dd>
							<dt>학번</dt><dd><%= resume.id_num %></dd>
							<dt>소속</dt><dd><%= resume.degree %></dd>
							<dt>지원부문</dt><dd><%= resume.position %></dd>
							<% JSON.parse(resume.answers).each do |qa| %>
							<dt><%= qa['q'] %></dt>
							<dd><%= qa['a'] %></dd>
							<% end %>
						</dl>
					</div>
				</div>
			</div>
			<% end %>
		</div>
	</div>
	<div class="row text-center">
		<div class="col-sm-12">
			<a href="/posts/<%=@post.id%>/edit"><button type="button" class="btn btn-lg btn-primary">수정하기</button></a>
		</div>
	</div>
	<% else %>
	<div class="row text-center">
		<div class="col-sm-12">
			<a href="/resumes/new?p=<%=@post.id%>">
			<input type="button" id="btn_apply" class="btn btn-lg btn-primary" value="지원하기">
		</a>
		</div>
	</div>
	<% end %>
</div>

sharamin/app/views/resumes/_form.html.erb
<%= form_for(resume) do |f| %>
  <% if resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% resume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="container">
		<div class="form-group row">
			<label for="example-text-input" class="col-2 col-form-label">이름</label>
			<div class="col-10">
				<%= f.text_field :name, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">학번</label>
			<div class="col-10">
				<%= f.text_field :id_num, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">소속 학과</label>
			<div class="col-10">
				<%= f.text_field :dept, class: 'form-control' %>
			</div>
		</div>

		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">학생 구분</label>
			<div class="col-10">
				<%= f.text_field :degree, class: 'form-control' %>
			</div>
		</div>
		<div class="form-group row">
			<label for="example-datetime-local-input" class="col-2 col-form-label">지원 부문</label>
			<div class="col-10">
				<%= f.text_field :position, class: 'form-control' %>
			</div>
		</div>
		<input id="qa_val" type="hidden" name="resume[answers]"/>
		<input type="hidden" name="resume[post_id]" value="<%= @post.id %>"/>
		<div id="qa_wrapper">
			<% JSON.parse(@post.questions).each_with_index do |q, i| %>
			<div class="form-group row">
				<label for="exampleTextarea" class="col-2 col-form-label"><%= i+1 %>. <%= q %></label>
				<div class="col-10">
					<textarea class="form-control" id="exampleTextarea" rows="8"></textarea>
				</div>
			</div>
			<% end %>
		</div>
		<div class="row text-center">
			<div class="col-sm-12">
			<button id="submit_btn" type="button" class="btn btn-lg btn-primary">지원서 제출</button>
			</div>
		</div>
	</div>
<% end %>
<script>
	$(document).ready(function() { 
		$("#submit_btn").click(function(e) {
			e.preventDefault();
			var qa = [];
			$("#qa_wrapper").children().each(function(i, item) {
				var q = $(item).find("label").text();
				var a = $(item).find("textarea").val();
				qa.push({q:q, a:a});
			});
			var qa_str = JSON.stringify(qa);
			$("#qa_val").val(qa_str);			
			$(this).parents('form').submit();
		});
	});
</script>

sharamin/app/views/resumes/edit.html.erb
<h1>Editing Resume</h1>

<%= render 'form', resume: @resume %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

sharamin/app/views/resumes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="row club_intro">
		<%= image_tag @post.logo_img.to_s, class:'logo_img float-left' %>
		<p>
			<%= @post.description %>
		</p>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong>모집부문</strong>
		</div>
		<div class="col-sm-">
			<%= @post.target %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong> 모집기간 </strong>
		</div>
		<div class="col-sm-10">
			<%= @post.deadline.strftime("%Y-%m-%d %H시 까지") %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong> 기타 사항 </strong>
		</div>
		<div class="col-sm-10">
			<%= @post.etc %>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">
			<strong> 홈페이지 주소 </strong>
		</div>
		<div class="col-sm-10">
			<a href="<%= @post.homepage %>" target="_blank"><%= @post.club %> 홈페이지</a>
		</div>
	</div>
	<div class="row attach_wrapper">
	<%= image_tag @post.attachment.to_s %>
	</div>
</div>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

sharamin/app/views/resumes/new.html.erb
<style>
.container {
	margin-bottom:20px;
}
</style>
<div class="container header">
	<div class="alert alert-info">
		<strong class="font_30">지원서를 작성하세요</strong>
	</div>
</div>

<%= render 'form', resume: @resume %>

sharamin/app/views/resumes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_resume_path(@resume) %> |
<%= link_to 'Back', resumes_path %>